version: '3.8'

volumes:
  mariadb:

networks:
  mariadb_net:
    name: mariadb_net
    driver: bridge

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    networks:
      - mariadb_net
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: MARIADB_ROOT_PASSWORD
      MARIADB_USER: mariadbuser 
      MARIADB_PASSWORD: mariadbpwd
      MARIADB_DATABASE: user_db

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 8181:80
    networks:
      - mariadb_net
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: mariadbuser
      PMA_PASSWORD: mariadbpwd


